### ISSUE TITLE
Migrate CLI and Configuration to Cobra + Viper

### ISSUE THREAD

**Issue by frrist** [storacha/piri#93]
## Description

The project currently uses `urfave/cli/v2` for command-line interface and has no unified configuration file support. Configuration is spread across CLI flags and environment variables, requiring operators to use both mechanisms. We should migrate to Cobra + Viper to provide a modern, feature-rich CLI experience with proper configuration file support.

## Current Behavior

- CLI uses `urfave/cli/v2` (seen in `cmd/storage/main.go`)
- Configuration via CLI flags and environment variables only
- No configuration file support
- Some settings only available as flags, others only as env vars 
  - I understand this was by design, though I lean towards parity among all configuration options, we can hide flags we don't want exposed.
- Operators must manage configuration across multiple mechanisms.
- Little to no configuration validation or defaults management.

## Expected Behavior

Migrate to Cobra + Viper to gain:
1. **Unified configuration**: Support for config files, env vars, and CLI flags with proper precedence
2. **Config file support**: TOML format for easy human editing
3. **Better CLI UX**: Auto-generated docs, shell completions, command aliases, persistent flags, etc.
  - Cobra features are a super-set of ufave/cli.
  - Cobra integrates seamlessly with viper (big 'ol pile of snakes)
5. **Configuration validation**: Type checking and required field validation
6. **Live config reload**: Change settings without restart (where applicable)
7. **12-factor app compliance**: Proper separation of config from code
### Benefits of Cobra + Viper

1. **Cobra Features**:
   - Auto-generated man pages and documentation
   - Shell completion for bash, zsh, fish, PowerShell
   - Intelligent command suggestions ("Did you mean...?")
   - Built-in help generation
   - Command aliases and hidden commands
   - Persistent and local flags
   - Pre/Post run hooks
   - **Most importantly, direct integration with viper.**

2. **Viper Features**:
   - Read from JSON, TOML, YAML, HCL, envfile and Java properties
   - Live watching and re-reading of config files
   - Reading from environment variables
   - Setting defaults
   - Reading from remote config systems (etcd, Consul)
   - Type-safe configuration access
   - Automatic environment variable binding

3. **Configuration Precedence** (highest to lowest):
   1. CLI flags
   2. Environment variables
   3. Config file
   4. Default values

### Proposed Configuration Structure

**Config File Location**: `~/.piri/config.toml` (or specified via `--config`)

**Example `config.toml`**:
```toml
# API Configuration
[api]
listen = ":8080"
auth_enabled = true
auth_service_name = "pdp-client"
trusted_principals = ["did:key:z6Mkk..."]

# Database Configuration
[taskengine.database]
type = "sqlite"
path = "/var/lib/piri/engine.db"
max_connections = 25
timeout = "30s"

[aggregator.database]
type = "sqlite"
path = "/var/lib/piri/aggregator.db"
max_connections = 25
timeout = "30s"

# Storage Configuration
[storage]
type = "filesystem"  # or "s3"
path = "/var/lib/piri/storage"

# S3 Storage (when type = "s3")
[storage.s3]
endpoint = "https://s3.amazonaws.com"
region = "us-east-1"
bucket = "piri-storage"
access_key_id = "${AWS_ACCESS_KEY_ID}"  # Can reference env vars
secret_access_key = "${AWS_SECRET_ACCESS_KEY}"

# PDP Configuration
[pdp]
proof_set_id = 1
contract_address = "0x..."
rpc_endpoint = "https://lotus.some.endpoint/v2/..."

# Task Scheduler
[scheduler]
workers = 10
poll_interval = "5s"
retry_attempts = 3
retry_delay = "1m"

# Logging
[logging]
level = "info"
format = "json"
output = "stdout"

# Metrics
[metrics]
enabled = true
listen = ":9090"
path = "/metrics"


```

### Migration Plan (Optional) 

1. **Phase 1: Add Cobra/Viper alongside existing CLI**:
   - Create new `cmd/v2/` directory with Cobra implementation
   - Implement config file loading with Viper
   - Maintain backward compatibility

2. **Phase 2: Feature Parity**:
   - Implement all existing commands in Cobra
   - Map all environment variables to Viper
   - Add configuration validation

3. **Phase 3: Migration**:
   - Switch main.go to use Cobra
   - Deprecate urfave/cli usage
   - Update documentation

### Example Implementation

```go
// cmd/root.go
package cmd

import (
    "github.com/spf13/cobra"
    "github.com/spf13/viper"
)

var (
    cfgFile string
    rootCmd = &cobra.Command{
        Use:   "piri",
        Short: "Manage running a piri node",
    }
)

func init() {
    cobra.OnInitialize(initConfig)
    rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", 
        "config file (default is $HOME/.piri/config.toml)")
    
    // Bind flags to viper
    viper.BindPFlag("api.listen", rootCmd.PersistentFlags().Lookup("listen"))
}

func initConfig() {
    if cfgFile != "" {
        viper.SetConfigFile(cfgFile)
    } else {
        viper.AddConfigPath("$HOME/.piri")
        viper.SetConfigName("config")
        viper.SetConfigType("toml")
    }
    
    viper.AutomaticEnv()
    viper.SetEnvPrefix("PIRI")
    viper.ReadInConfig()
}
```

### 12-Factor App Principles

Following https://12factor.net/:
- **III. Config**: Store config in the environment (Viper supports this)
- **V. Build, release, run**: Config separated from code
- **X. Dev/prod parity**: Same config mechanism across environments

## Acceptance Criteria

- [ ] Cobra CLI framework integrated with all existing commands
- [ ] Viper configuration system supporting TOML files
- [ ] All current CLI flags available in new system, hiding uncommon ones when required.
- [ ] All environment variables mapped to configuration
- [ ] Configuration file schema documented
- [ ] Default configuration file with sensible defaults
- [ ] Config validation with helpful error messages
- [ ] Shell completion scripts generated for major shells
- [ ] Migration guide for operators
- [ ] Unit tests for configuration loading and validation
- [ ] Backward compatibility during transition period
- [ ] `piri config` command to:
  - Generate default config
  - Validate config file
  - Show effective configuration
- [ ] Documentation includes:
  - Configuration reference
  - Migration guide from env vars/flags
  - Example configurations

## Additional Context

- This migration provides foundation for Issue https://github.com/storacha/piri/issues/94 (S3 blobstore config)
- Viper's live reload could enable dynamic log level changes (Issue https://github.com/storacha/piri/issues/97)
- Structured config makes it easier to add new features
- Consider using `viper.Unmarshal()` with struct tags for type safety
- Future enhancement: Support for multiple config files (includes)
- The config file format (TOML) is readable and well-supported
- This change significantly improves operator experience
